# Generated by Django 4.1.1 on 2022-09-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartproducts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproducts",
            name="productValue",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
