# Generated by Django 4.1.1 on 2022-09-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartproducts", "0002_alter_cartproducts_productvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproducts",
            name="productValue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
