# Generated by Django 4.1.1 on 2022-09-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=150)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=3, max_digits=4),
                ),
            ],
        ),
    ]
