# Generated by Django 4.1.1 on 2022-09-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="name",
        ),
        migrations.AlterField(
            model_name="discount",
            name="discount_percent",
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
