# Generated by Django 4.1.1 on 2022-09-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="subtotal",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
