# Generated by Django 4.1.1 on 2022-09-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
