# Generated by Django 4.1.1 on 2022-09-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("discounts", "0002_remove_discount_name_alter_discount_discount_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                ("category_id", models.PositiveIntegerField(default=1)),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount_id", models.PositiveIntegerField(default=1)),
                (
                    "product_category",
                    models.ManyToManyField(
                        related_name="products", to="categories.category"
                    ),
                ),
                (
                    "product_discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="discounts.discount",
                    ),
                ),
            ],
        ),
    ]
