# Generated by Django 4.1.1 on 2022-09-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("products", "0002_remove_product_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_category",
        ),
        migrations.AddField(
            model_name="product",
            name="product_category",
            field=models.ManyToManyField(
                related_name="products", to="categories.category"
            ),
        ),
    ]
