# Generated by Django 4.1.1 on 2022-09-12 23:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_category_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category_id",
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
